kind: pipeline
type: docker
name: venlab-landing


pipeline:
  deployment:
    image: appleboy/drone-ssh
    host: venlab.dev
    settings:
      key:
        from_secret: password
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      port:
        from_secret: ssh_port
      script:
        - cd "$VENLAB_BASE" && bash deploy.sh

trigger:
  branch:
  - master
  - drone
