kind: pipeline
type: docker
name: venlab-landing


pipeline:
  deployment:
    image: appleboy/drone-ssh
    settings:
      host: venlab.dev
      username: root
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd "$VENLAB_BASE" && bash deploy.sh

trigger:
  branch:
  - master
  - drone
