kind: pipeline
type: docker
name: venlab-landing


pipeline:
  deployment:
    image: appleboy/drone-ssh
    host: venlab.dev
    key:
      from_secret: password
    username:
      from_secret: ssh_username
    port:
      from_secret: ssh_port
    script:
        - bash deploy.sh

trigger:
  branch:
  - master
  - drone
